/*
 * generated by Xtext
 */
package de.nordakademie.mwi13a.team1.survey.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SurveyUiModule extends de.nordakademie.mwi13a.team1.survey.ui.AbstractSurveyUiModule {
	public SurveyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
