/*
* generated by Xtext
*/
package de.nordakademie.mwi13a.team1.dependency.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class DependencyGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class DependencyModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DependencyModel");
		private final Assignment cElementsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cElementsSurveyElementsParserRuleCall_0 = (RuleCall)cElementsAssignment.eContents().get(0);
		
		//DependencyModel:
		//	elements+=SurveyElements+;
		public ParserRule getRule() { return rule; }

		//elements+=SurveyElements+
		public Assignment getElementsAssignment() { return cElementsAssignment; }

		//SurveyElements
		public RuleCall getElementsSurveyElementsParserRuleCall_0() { return cElementsSurveyElementsParserRuleCall_0; }
	}

	public class SurveyElementsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SurveyElements");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSurveyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cNameQuestionnaireCrossReference_1_0 = (CrossReference)cNameAssignment_1.eContents().get(0);
		private final RuleCall cNameQuestionnaireSTRINGTerminalRuleCall_1_0_1 = (RuleCall)cNameQuestionnaireCrossReference_1_0.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cPartElementsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPartElementsPartElementsParserRuleCall_3_0 = (RuleCall)cPartElementsAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SurveyElements:
		//	"Survey:" name=[surveyImp::Questionnaire|STRING] "{" partElements+=PartElements+ "}";
		public ParserRule getRule() { return rule; }

		//"Survey:" name=[surveyImp::Questionnaire|STRING] "{" partElements+=PartElements+ "}"
		public Group getGroup() { return cGroup; }

		//"Survey:"
		public Keyword getSurveyKeyword_0() { return cSurveyKeyword_0; }

		//name=[surveyImp::Questionnaire|STRING]
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//[surveyImp::Questionnaire|STRING]
		public CrossReference getNameQuestionnaireCrossReference_1_0() { return cNameQuestionnaireCrossReference_1_0; }

		//STRING
		public RuleCall getNameQuestionnaireSTRINGTerminalRuleCall_1_0_1() { return cNameQuestionnaireSTRINGTerminalRuleCall_1_0_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//partElements+=PartElements+
		public Assignment getPartElementsAssignment_3() { return cPartElementsAssignment_3; }

		//PartElements
		public RuleCall getPartElementsPartElementsParserRuleCall_3_0() { return cPartElementsPartElementsParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class PartElementsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PartElements");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cNamePartCrossReference_1_0 = (CrossReference)cNameAssignment_1.eContents().get(0);
		private final RuleCall cNamePartSTRINGTerminalRuleCall_1_0_1 = (RuleCall)cNamePartCrossReference_1_0.eContents().get(1);
		private final Assignment cOptionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOptionPartOptionsParserRuleCall_2_0 = (RuleCall)cOptionAssignment_2.eContents().get(0);
		
		//PartElements:
		//	"Part:" name=[surveyImp::Part|STRING] option=PartOptions;
		public ParserRule getRule() { return rule; }

		//"Part:" name=[surveyImp::Part|STRING] option=PartOptions
		public Group getGroup() { return cGroup; }

		//"Part:"
		public Keyword getPartKeyword_0() { return cPartKeyword_0; }

		//name=[surveyImp::Part|STRING]
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//[surveyImp::Part|STRING]
		public CrossReference getNamePartCrossReference_1_0() { return cNamePartCrossReference_1_0; }

		//STRING
		public RuleCall getNamePartSTRINGTerminalRuleCall_1_0_1() { return cNamePartSTRINGTerminalRuleCall_1_0_1; }

		//option=PartOptions
		public Assignment getOptionAssignment_2() { return cOptionAssignment_2; }

		//PartOptions
		public RuleCall getOptionPartOptionsParserRuleCall_2_0() { return cOptionPartOptionsParserRuleCall_2_0; }
	}

	public class PartOptionsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PartOptions");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cDefineNextPartAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cNextPartsKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cNextPartsAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cNextPartsDMNextPartsParserRuleCall_0_2_0 = (RuleCall)cNextPartsAssignment_0_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cLastPartAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cLastPartAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Keyword cLastPartLastPartKeyword_1_1_0 = (Keyword)cLastPartAssignment_1_1.eContents().get(0);
		
		//PartOptions:
		//	{DefineNextPart} "Next parts {" nextParts+=DMNextParts+ "}" | {LastPart} lastPart?="LastPart";
		public ParserRule getRule() { return rule; }

		//{DefineNextPart} "Next parts {" nextParts+=DMNextParts+ "}" | {LastPart} lastPart?="LastPart"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{DefineNextPart} "Next parts {" nextParts+=DMNextParts+ "}"
		public Group getGroup_0() { return cGroup_0; }

		//{DefineNextPart}
		public Action getDefineNextPartAction_0_0() { return cDefineNextPartAction_0_0; }

		//"Next parts {"
		public Keyword getNextPartsKeyword_0_1() { return cNextPartsKeyword_0_1; }

		//nextParts+=DMNextParts+
		public Assignment getNextPartsAssignment_0_2() { return cNextPartsAssignment_0_2; }

		//DMNextParts
		public RuleCall getNextPartsDMNextPartsParserRuleCall_0_2_0() { return cNextPartsDMNextPartsParserRuleCall_0_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_0_3() { return cRightCurlyBracketKeyword_0_3; }

		//{LastPart} lastPart?="LastPart"
		public Group getGroup_1() { return cGroup_1; }

		//{LastPart}
		public Action getLastPartAction_1_0() { return cLastPartAction_1_0; }

		//lastPart?="LastPart"
		public Assignment getLastPartAssignment_1_1() { return cLastPartAssignment_1_1; }

		//"LastPart"
		public Keyword getLastPartLastPartKeyword_1_1_0() { return cLastPartLastPartKeyword_1_1_0; }
	}

	public class DMNextPartsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DMNextParts");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNextPartKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cNamePartCrossReference_1_0 = (CrossReference)cNameAssignment_1.eContents().get(0);
		private final RuleCall cNamePartSTRINGTerminalRuleCall_1_0_1 = (RuleCall)cNamePartCrossReference_1_0.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cPartDependenciesKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final Assignment cExpressionsAssignment_2_2 = (Assignment)cGroup_2.eContents().get(2);
		private final RuleCall cExpressionsDependencyParserRuleCall_2_2_0 = (RuleCall)cExpressionsAssignment_2_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_2_3 = (Keyword)cGroup_2.eContents().get(3);
		
		//DMNextParts:
		//	"Next part:" name=[surveyImp::Part|STRING] ("Part dependencies" "{" expressions+=Dependency+ "}")?;
		public ParserRule getRule() { return rule; }

		//"Next part:" name=[surveyImp::Part|STRING] ("Part dependencies" "{" expressions+=Dependency+ "}")?
		public Group getGroup() { return cGroup; }

		//"Next part:"
		public Keyword getNextPartKeyword_0() { return cNextPartKeyword_0; }

		//name=[surveyImp::Part|STRING]
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//[surveyImp::Part|STRING]
		public CrossReference getNamePartCrossReference_1_0() { return cNamePartCrossReference_1_0; }

		//STRING
		public RuleCall getNamePartSTRINGTerminalRuleCall_1_0_1() { return cNamePartSTRINGTerminalRuleCall_1_0_1; }

		//("Part dependencies" "{" expressions+=Dependency+ "}")?
		public Group getGroup_2() { return cGroup_2; }

		//"Part dependencies"
		public Keyword getPartDependenciesKeyword_2_0() { return cPartDependenciesKeyword_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2_1() { return cLeftCurlyBracketKeyword_2_1; }

		//expressions+=Dependency+
		public Assignment getExpressionsAssignment_2_2() { return cExpressionsAssignment_2_2; }

		//Dependency
		public RuleCall getExpressionsDependencyParserRuleCall_2_2_0() { return cExpressionsDependencyParserRuleCall_2_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_2_3() { return cRightCurlyBracketKeyword_2_3; }
	}

	public class DependencyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Dependency");
		private final RuleCall cOrParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Dependency:
		//	Or;
		public ParserRule getRule() { return rule; }

		//Or
		public RuleCall getOrParserRuleCall() { return cOrParserRuleCall; }
	}

	public class OrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Or");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cAndParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cOrLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cORKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightAndParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Or returns Dependency:
		//	And ({Or.left=current} "OR" right=And)*;
		public ParserRule getRule() { return rule; }

		//And ({Or.left=current} "OR" right=And)*
		public Group getGroup() { return cGroup; }

		//And
		public RuleCall getAndParserRuleCall_0() { return cAndParserRuleCall_0; }

		//({Or.left=current} "OR" right=And)*
		public Group getGroup_1() { return cGroup_1; }

		//{Or.left=current}
		public Action getOrLeftAction_1_0() { return cOrLeftAction_1_0; }

		//"OR"
		public Keyword getORKeyword_1_1() { return cORKeyword_1_1; }

		//right=And
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//And
		public RuleCall getRightAndParserRuleCall_1_2_0() { return cRightAndParserRuleCall_1_2_0; }
	}

	public class AndElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "And");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAndLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cANDKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//And returns Dependency:
		//	Primary ({And.left=current} "AND" right=Primary)*;
		public ParserRule getRule() { return rule; }

		//Primary ({And.left=current} "AND" right=Primary)*
		public Group getGroup() { return cGroup; }

		//Primary
		public RuleCall getPrimaryParserRuleCall_0() { return cPrimaryParserRuleCall_0; }

		//({And.left=current} "AND" right=Primary)*
		public Group getGroup_1() { return cGroup_1; }

		//{And.left=current}
		public Action getAndLeftAction_1_0() { return cAndLeftAction_1_0; }

		//"AND"
		public Keyword getANDKeyword_1_1() { return cANDKeyword_1_1; }

		//right=Primary
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }

		//Primary
		public RuleCall getRightPrimaryParserRuleCall_1_2_0() { return cRightPrimaryParserRuleCall_1_2_0; }
	}

	public class PrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Primary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cBracketAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cLeftParenthesisKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cDependencyAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cDependencyOrParserRuleCall_0_2_0 = (RuleCall)cDependencyAssignment_0_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final RuleCall cAtomicParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Primary returns Dependency:
		//	{Bracket} "(" dependency=Or ")" | Atomic;
		public ParserRule getRule() { return rule; }

		//{Bracket} "(" dependency=Or ")" | Atomic
		public Alternatives getAlternatives() { return cAlternatives; }

		//{Bracket} "(" dependency=Or ")"
		public Group getGroup_0() { return cGroup_0; }

		//{Bracket}
		public Action getBracketAction_0_0() { return cBracketAction_0_0; }

		//"("
		public Keyword getLeftParenthesisKeyword_0_1() { return cLeftParenthesisKeyword_0_1; }

		//dependency=Or
		public Assignment getDependencyAssignment_0_2() { return cDependencyAssignment_0_2; }

		//Or
		public RuleCall getDependencyOrParserRuleCall_0_2_0() { return cDependencyOrParserRuleCall_0_2_0; }

		//")"
		public Keyword getRightParenthesisKeyword_0_3() { return cRightParenthesisKeyword_0_3; }

		//Atomic
		public RuleCall getAtomicParserRuleCall_1() { return cAtomicParserRuleCall_1; }
	}

	public class AtomicElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Atomic");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cDMQuestionAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Keyword cQuestionKeyword_0_1 = (Keyword)cGroup_0.eContents().get(1);
		private final Assignment cQuestionAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final CrossReference cQuestionQuestionCrossReference_0_2_0 = (CrossReference)cQuestionAssignment_0_2.eContents().get(0);
		private final RuleCall cQuestionQuestionSTRINGTerminalRuleCall_0_2_0_1 = (RuleCall)cQuestionQuestionCrossReference_0_2_0.eContents().get(1);
		private final Keyword cAnswerKeyword_0_3 = (Keyword)cGroup_0.eContents().get(3);
		private final Assignment cAnswerAssignment_0_4 = (Assignment)cGroup_0.eContents().get(4);
		private final CrossReference cAnswerAnswerCrossReference_0_4_0 = (CrossReference)cAnswerAssignment_0_4.eContents().get(0);
		private final RuleCall cAnswerAnswerSTRINGTerminalRuleCall_0_4_0_1 = (RuleCall)cAnswerAnswerCrossReference_0_4_0.eContents().get(1);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cDMMatrixQuestionAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Keyword cMatrixQuestionKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		private final Assignment cQuestionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final CrossReference cQuestionMatrixQuestionCrossReference_1_2_0 = (CrossReference)cQuestionAssignment_1_2.eContents().get(0);
		private final RuleCall cQuestionMatrixQuestionSTRINGTerminalRuleCall_1_2_0_1 = (RuleCall)cQuestionMatrixQuestionCrossReference_1_2_0.eContents().get(1);
		private final Keyword cAnswerKeyword_1_3 = (Keyword)cGroup_1.eContents().get(3);
		private final Assignment cAnswerAssignment_1_4 = (Assignment)cGroup_1.eContents().get(4);
		private final CrossReference cAnswerAnswerCrossReference_1_4_0 = (CrossReference)cAnswerAssignment_1_4.eContents().get(0);
		private final RuleCall cAnswerAnswerSTRINGTerminalRuleCall_1_4_0_1 = (RuleCall)cAnswerAnswerCrossReference_1_4_0.eContents().get(1);
		
		//Atomic returns Dependency:
		//	{DMQuestion} "Question:" question=[surveyImp::Question|STRING] "Answer:" answer=[surveyImp::Answer|STRING] |
		//	{DMMatrixQuestion} "Matrix Question:" question=[surveyImp::MatrixQuestion|STRING] "Answer:"
		//	answer=[surveyImp::Answer|STRING];
		public ParserRule getRule() { return rule; }

		//{DMQuestion} "Question:" question=[surveyImp::Question|STRING] "Answer:" answer=[surveyImp::Answer|STRING] |
		//{DMMatrixQuestion} "Matrix Question:" question=[surveyImp::MatrixQuestion|STRING] "Answer:"
		//answer=[surveyImp::Answer|STRING]
		public Alternatives getAlternatives() { return cAlternatives; }

		//{DMQuestion} "Question:" question=[surveyImp::Question|STRING] "Answer:" answer=[surveyImp::Answer|STRING]
		public Group getGroup_0() { return cGroup_0; }

		//{DMQuestion}
		public Action getDMQuestionAction_0_0() { return cDMQuestionAction_0_0; }

		//"Question:"
		public Keyword getQuestionKeyword_0_1() { return cQuestionKeyword_0_1; }

		//question=[surveyImp::Question|STRING]
		public Assignment getQuestionAssignment_0_2() { return cQuestionAssignment_0_2; }

		//[surveyImp::Question|STRING]
		public CrossReference getQuestionQuestionCrossReference_0_2_0() { return cQuestionQuestionCrossReference_0_2_0; }

		//STRING
		public RuleCall getQuestionQuestionSTRINGTerminalRuleCall_0_2_0_1() { return cQuestionQuestionSTRINGTerminalRuleCall_0_2_0_1; }

		//"Answer:"
		public Keyword getAnswerKeyword_0_3() { return cAnswerKeyword_0_3; }

		//answer=[surveyImp::Answer|STRING]
		public Assignment getAnswerAssignment_0_4() { return cAnswerAssignment_0_4; }

		//[surveyImp::Answer|STRING]
		public CrossReference getAnswerAnswerCrossReference_0_4_0() { return cAnswerAnswerCrossReference_0_4_0; }

		//STRING
		public RuleCall getAnswerAnswerSTRINGTerminalRuleCall_0_4_0_1() { return cAnswerAnswerSTRINGTerminalRuleCall_0_4_0_1; }

		//{DMMatrixQuestion} "Matrix Question:" question=[surveyImp::MatrixQuestion|STRING] "Answer:"
		//answer=[surveyImp::Answer|STRING]
		public Group getGroup_1() { return cGroup_1; }

		//{DMMatrixQuestion}
		public Action getDMMatrixQuestionAction_1_0() { return cDMMatrixQuestionAction_1_0; }

		//"Matrix Question:"
		public Keyword getMatrixQuestionKeyword_1_1() { return cMatrixQuestionKeyword_1_1; }

		//question=[surveyImp::MatrixQuestion|STRING]
		public Assignment getQuestionAssignment_1_2() { return cQuestionAssignment_1_2; }

		//[surveyImp::MatrixQuestion|STRING]
		public CrossReference getQuestionMatrixQuestionCrossReference_1_2_0() { return cQuestionMatrixQuestionCrossReference_1_2_0; }

		//STRING
		public RuleCall getQuestionMatrixQuestionSTRINGTerminalRuleCall_1_2_0_1() { return cQuestionMatrixQuestionSTRINGTerminalRuleCall_1_2_0_1; }

		//"Answer:"
		public Keyword getAnswerKeyword_1_3() { return cAnswerKeyword_1_3; }

		//answer=[surveyImp::Answer|STRING]
		public Assignment getAnswerAssignment_1_4() { return cAnswerAssignment_1_4; }

		//[surveyImp::Answer|STRING]
		public CrossReference getAnswerAnswerCrossReference_1_4_0() { return cAnswerAnswerCrossReference_1_4_0; }

		//STRING
		public RuleCall getAnswerAnswerSTRINGTerminalRuleCall_1_4_0_1() { return cAnswerAnswerSTRINGTerminalRuleCall_1_4_0_1; }
	}

	public class DMMatrixQuestionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DMMatrixQuestion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMatrixQuestionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMatrixQuestionAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cMatrixQuestionMatrixQuestionCrossReference_1_0 = (CrossReference)cMatrixQuestionAssignment_1.eContents().get(0);
		private final RuleCall cMatrixQuestionMatrixQuestionSTRINGTerminalRuleCall_1_0_1 = (RuleCall)cMatrixQuestionMatrixQuestionCrossReference_1_0.eContents().get(1);
		private final Keyword cMatrixScaleKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMatrixScaleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cMatrixScaleAnswerCrossReference_3_0 = (CrossReference)cMatrixScaleAssignment_3.eContents().get(0);
		private final RuleCall cMatrixScaleAnswerSTRINGTerminalRuleCall_3_0_1 = (RuleCall)cMatrixScaleAnswerCrossReference_3_0.eContents().get(1);
		
		//DMMatrixQuestion:
		//	"Matrix Question:" matrixQuestion=[surveyImp::MatrixQuestion|STRING] "Matrix Scale:"
		//	matrixScale=[surveyImp::Answer|STRING];
		public ParserRule getRule() { return rule; }

		//"Matrix Question:" matrixQuestion=[surveyImp::MatrixQuestion|STRING] "Matrix Scale:"
		//matrixScale=[surveyImp::Answer|STRING]
		public Group getGroup() { return cGroup; }

		//"Matrix Question:"
		public Keyword getMatrixQuestionKeyword_0() { return cMatrixQuestionKeyword_0; }

		//matrixQuestion=[surveyImp::MatrixQuestion|STRING]
		public Assignment getMatrixQuestionAssignment_1() { return cMatrixQuestionAssignment_1; }

		//[surveyImp::MatrixQuestion|STRING]
		public CrossReference getMatrixQuestionMatrixQuestionCrossReference_1_0() { return cMatrixQuestionMatrixQuestionCrossReference_1_0; }

		//STRING
		public RuleCall getMatrixQuestionMatrixQuestionSTRINGTerminalRuleCall_1_0_1() { return cMatrixQuestionMatrixQuestionSTRINGTerminalRuleCall_1_0_1; }

		//"Matrix Scale:"
		public Keyword getMatrixScaleKeyword_2() { return cMatrixScaleKeyword_2; }

		//matrixScale=[surveyImp::Answer|STRING]
		public Assignment getMatrixScaleAssignment_3() { return cMatrixScaleAssignment_3; }

		//[surveyImp::Answer|STRING]
		public CrossReference getMatrixScaleAnswerCrossReference_3_0() { return cMatrixScaleAnswerCrossReference_3_0; }

		//STRING
		public RuleCall getMatrixScaleAnswerSTRINGTerminalRuleCall_3_0_1() { return cMatrixScaleAnswerSTRINGTerminalRuleCall_3_0_1; }
	}

	public class IdentifierElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Identifier");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIDTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSTRINGTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Identifier:
		//	ID | STRING | INT;
		public ParserRule getRule() { return rule; }

		//ID | STRING | INT
		public Alternatives getAlternatives() { return cAlternatives; }

		//ID
		public RuleCall getIDTerminalRuleCall_0() { return cIDTerminalRuleCall_0; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_1() { return cSTRINGTerminalRuleCall_1; }

		//INT
		public RuleCall getINTTerminalRuleCall_2() { return cINTTerminalRuleCall_2; }
	}
	
	
	private DependencyModelElements pDependencyModel;
	private SurveyElementsElements pSurveyElements;
	private PartElementsElements pPartElements;
	private PartOptionsElements pPartOptions;
	private DMNextPartsElements pDMNextParts;
	private DependencyElements pDependency;
	private OrElements pOr;
	private AndElements pAnd;
	private PrimaryElements pPrimary;
	private AtomicElements pAtomic;
	private DMMatrixQuestionElements pDMMatrixQuestion;
	private IdentifierElements pIdentifier;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public DependencyGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("de.nordakademie.mwi13a.team1.dependency.Dependency".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//DependencyModel:
	//	elements+=SurveyElements+;
	public DependencyModelElements getDependencyModelAccess() {
		return (pDependencyModel != null) ? pDependencyModel : (pDependencyModel = new DependencyModelElements());
	}
	
	public ParserRule getDependencyModelRule() {
		return getDependencyModelAccess().getRule();
	}

	//SurveyElements:
	//	"Survey:" name=[surveyImp::Questionnaire|STRING] "{" partElements+=PartElements+ "}";
	public SurveyElementsElements getSurveyElementsAccess() {
		return (pSurveyElements != null) ? pSurveyElements : (pSurveyElements = new SurveyElementsElements());
	}
	
	public ParserRule getSurveyElementsRule() {
		return getSurveyElementsAccess().getRule();
	}

	//PartElements:
	//	"Part:" name=[surveyImp::Part|STRING] option=PartOptions;
	public PartElementsElements getPartElementsAccess() {
		return (pPartElements != null) ? pPartElements : (pPartElements = new PartElementsElements());
	}
	
	public ParserRule getPartElementsRule() {
		return getPartElementsAccess().getRule();
	}

	//PartOptions:
	//	{DefineNextPart} "Next parts {" nextParts+=DMNextParts+ "}" | {LastPart} lastPart?="LastPart";
	public PartOptionsElements getPartOptionsAccess() {
		return (pPartOptions != null) ? pPartOptions : (pPartOptions = new PartOptionsElements());
	}
	
	public ParserRule getPartOptionsRule() {
		return getPartOptionsAccess().getRule();
	}

	//DMNextParts:
	//	"Next part:" name=[surveyImp::Part|STRING] ("Part dependencies" "{" expressions+=Dependency+ "}")?;
	public DMNextPartsElements getDMNextPartsAccess() {
		return (pDMNextParts != null) ? pDMNextParts : (pDMNextParts = new DMNextPartsElements());
	}
	
	public ParserRule getDMNextPartsRule() {
		return getDMNextPartsAccess().getRule();
	}

	//Dependency:
	//	Or;
	public DependencyElements getDependencyAccess() {
		return (pDependency != null) ? pDependency : (pDependency = new DependencyElements());
	}
	
	public ParserRule getDependencyRule() {
		return getDependencyAccess().getRule();
	}

	//Or returns Dependency:
	//	And ({Or.left=current} "OR" right=And)*;
	public OrElements getOrAccess() {
		return (pOr != null) ? pOr : (pOr = new OrElements());
	}
	
	public ParserRule getOrRule() {
		return getOrAccess().getRule();
	}

	//And returns Dependency:
	//	Primary ({And.left=current} "AND" right=Primary)*;
	public AndElements getAndAccess() {
		return (pAnd != null) ? pAnd : (pAnd = new AndElements());
	}
	
	public ParserRule getAndRule() {
		return getAndAccess().getRule();
	}

	//Primary returns Dependency:
	//	{Bracket} "(" dependency=Or ")" | Atomic;
	public PrimaryElements getPrimaryAccess() {
		return (pPrimary != null) ? pPrimary : (pPrimary = new PrimaryElements());
	}
	
	public ParserRule getPrimaryRule() {
		return getPrimaryAccess().getRule();
	}

	//Atomic returns Dependency:
	//	{DMQuestion} "Question:" question=[surveyImp::Question|STRING] "Answer:" answer=[surveyImp::Answer|STRING] |
	//	{DMMatrixQuestion} "Matrix Question:" question=[surveyImp::MatrixQuestion|STRING] "Answer:"
	//	answer=[surveyImp::Answer|STRING];
	public AtomicElements getAtomicAccess() {
		return (pAtomic != null) ? pAtomic : (pAtomic = new AtomicElements());
	}
	
	public ParserRule getAtomicRule() {
		return getAtomicAccess().getRule();
	}

	//DMMatrixQuestion:
	//	"Matrix Question:" matrixQuestion=[surveyImp::MatrixQuestion|STRING] "Matrix Scale:"
	//	matrixScale=[surveyImp::Answer|STRING];
	public DMMatrixQuestionElements getDMMatrixQuestionAccess() {
		return (pDMMatrixQuestion != null) ? pDMMatrixQuestion : (pDMMatrixQuestion = new DMMatrixQuestionElements());
	}
	
	public ParserRule getDMMatrixQuestionRule() {
		return getDMMatrixQuestionAccess().getRule();
	}

	//Identifier:
	//	ID | STRING | INT;
	public IdentifierElements getIdentifierAccess() {
		return (pIdentifier != null) ? pIdentifier : (pIdentifier = new IdentifierElements());
	}
	
	public ParserRule getIdentifierRule() {
		return getIdentifierAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
