/*
 * generated by Xtext
 */
package de.nordakademie.mwi13a.team1.survey.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import de.nordakademie.mwi13a.team1.survey.ui.internal.SurveyActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class SurveyExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return SurveyActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return SurveyActivator.getInstance().getInjector(SurveyActivator.DE_NORDAKADEMIE_MWI13A_TEAM1_SURVEY_SURVEY);
	}
	
}
