/*
 * generated by Xtext
 */
package de.nordakademie.mwi13a.team1.dependency.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DependencyUiModule extends de.nordakademie.mwi13a.team1.dependency.ui.AbstractDependencyUiModule {
	public DependencyUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
