/*
 * generated by Xtext
 */
package de.nordakademie.mwi13a.team1.dependency.ui.contentassist

import de.nordakademie.mwi13a.team1.dependency.ui.contentassist.AbstractDependencyProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DependencyProposalProvider extends AbstractDependencyProposalProvider {
}
