/*
* generated by Xtext
*/
package de.nordakademie.mwi13a.team1.dependency;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class DependencyUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return de.nordakademie.mwi13a.team1.dependency.ui.internal.DependencyActivator.getInstance().getInjector("de.nordakademie.mwi13a.team1.dependency.Dependency");
	}
	
}
