/*
 * generated by Xtext
 */
package de.nordakademie.mwi13a.team1.dependency.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDependencyValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(de.nordakademie.mwi13a.team1.dependency.dependency.DependencyPackage.eINSTANCE);
		return result;
	}
}
