/*
* generated by Xtext
*/
package de.nordakademie.mwi13a.team1.dependency.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.nordakademie.mwi13a.team1.dependency.services.DependencyGrammarAccess;

public class DependencyParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DependencyGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.nordakademie.mwi13a.team1.dependency.parser.antlr.internal.InternalDependencyParser createParser(XtextTokenStream stream) {
		return new de.nordakademie.mwi13a.team1.dependency.parser.antlr.internal.InternalDependencyParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "DependencyModel";
	}
	
	public DependencyGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DependencyGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
