/*
 * generated by Xtext
 */
package de.nordakademie.mwi13a.team1.survey.ui.contentassist

import de.nordakademie.mwi13a.team1.survey.ui.contentassist.AbstractSurveyProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class SurveyProposalProvider extends AbstractSurveyProposalProvider {
}
