/*
* generated by Xtext
*/
package de.nordakademie.mwi13a.team1.survey;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SurveyStandaloneSetup extends SurveyStandaloneSetupGenerated{

	public static void doSetup() {
		new SurveyStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

