/*
 * generated by Xtext
 */
package de.nordakademie.mwi13a.team1.survey;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SurveyRuntimeModule extends de.nordakademie.mwi13a.team1.survey.AbstractSurveyRuntimeModule {

}
